<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_riwayat_kapal_model extends CI_Model
{

    public $table = 'tbl_riwayat_kapal';
    public $id = 'id_riwayat';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->select('*, tbl_riwayat_kapal.status');
        $this->db->order_by($this->id, $this->order);
        $this->db->join('tbl_kapal', 'tbl_kapal.id_kapal = tbl_riwayat_kapal.id_kapal');
        
        return $this->db->get($this->table)->result();
    }


    function get_by_date($awal, $akhir)
    {
        $this->db->select('*, tbl_riwayat_kapal.status');
        $this->db->order_by($this->id, $this->order);
        $this->db->join('tbl_kapal', 'tbl_kapal.id_kapal = tbl_riwayat_kapal.id_kapal');
        $this->db->where("tanggal_update BETWEEN '$awal' AND '$akhir'");
        return $this->db->get($this->table)->result();
    }


    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_riwayat', $q);
	$this->db->or_like('id_kapal', $q);
	$this->db->or_like('jam_update', $q);
	$this->db->or_like('muatan', $q);
	$this->db->or_like('pelabuhan_asal', $q);
	$this->db->or_like('pelabuhan_tujuan', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('tanggal_update', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_riwayat', $q);
	$this->db->or_like('id_kapal', $q);
	$this->db->or_like('jam_update', $q);
	$this->db->or_like('muatan', $q);
	$this->db->or_like('pelabuhan_asal', $q);
	$this->db->or_like('pelabuhan_tujuan', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('tanggal_update', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tbl_riwayat_kapal_model.php */
/* Location: ./application/models/Tbl_riwayat_kapal_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2025-02-06 07:10:57 */
/* http://harviacode.com */