<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_kapal_perbaikan_model extends CI_Model
{

    public $table = 'tbl_kapal_perbaikan';
    public $id = 'id_kapal_perbaikan';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->join('tbl_kapal', 'tbl_kapal.id_kapal = tbl_kapal_perbaikan.id_kapal');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function get_by_date($awal, $akhir)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->join('tbl_kapal', 'tbl_kapal.id_kapal = tbl_kapal_perbaikan.id_kapal');
        $this->db->where("tanggal_mulai BETWEEN '$awal' AND '$akhir'");
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_kapal_perbaikan', $q);
	$this->db->or_like('id_kapal', $q);
	$this->db->or_like('tanggal_mulai', $q);
	$this->db->or_like('tanggal_selesai', $q);
	$this->db->or_like('jenis_perbaikan', $q);
	$this->db->or_like('biaya_perbaikan', $q);
	$this->db->or_like('lokasi_perbaikan', $q);
	$this->db->or_like('teknisi_perbaikan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_kapal_perbaikan', $q);
	$this->db->or_like('id_kapal', $q);
	$this->db->or_like('tanggal_mulai', $q);
	$this->db->or_like('tanggal_selesai', $q);
	$this->db->or_like('jenis_perbaikan', $q);
	$this->db->or_like('biaya_perbaikan', $q);
	$this->db->or_like('lokasi_perbaikan', $q);
	$this->db->or_like('teknisi_perbaikan', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tbl_kapal_perbaikan_model.php */
/* Location: ./application/models/Tbl_kapal_perbaikan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2025-01-21 08:31:11 */
/* http://harviacode.com */